### ISSUE TITLE
vendor not publishing 

### ISSUE THREAD

**Issue by azarzaza** [ARCANEDEV/Notify#5]
vendor not publishing

**Comment by arcanedev-maroc** [comment]
Did you followed [these steps](https://github.com/ARCANEDEV/Notify/blob/master/_docs/2-Installation-and-Setup.md) ?

The only publishable file is the `notify` config file.

**Comment by azarzaza** [comment]
i tried but not published any file in config folder
i am using laravel 5.1

**Comment by arcanedev-maroc** [comment]
OK, i'm going to test the package and see if i got the same issue.

**Comment by arcanedev-maroc** [comment]
![notify-with-laravel-5 1](https://cloud.githubusercontent.com/assets/3282340/22370811/4c36cd3e-e48b-11e6-970d-3bf84c5c8810.png)

It works fine for me

**Comment by arcanedev-maroc** [comment]
Try this to force the publish command:

```shell
php artisan vendor:publish --provider="Arcanedev\Notify\NotifyServiceProvider" --force
```
